"""Offline agent observatory: normalized evidence import, classification, reporting.

This is a bounded foundation slice. It provides:

* a versioned normalized JSONL import contract (:mod:`contract`);
* a rebuildable, schema-versioned SQLite projection (:mod:`store`);
* conservative, non-executing command categorization (:mod:`commands`);
* a deterministic report (:mod:`report`);
* a Jev ``/v1/systemone`` request builder and saved-response validator
  (:mod:`jev`);
* shadow orchestration recommendations over a current configured catalog
  (:mod:`policy`), which are advisory and never modify routing;
* a pre-registered, opt-in, seeded randomized policy canary
  (:mod:`canary`) with a tested kill switch and a bounded request cap.

Live transport and collection are explicit and bounded: nothing crawls a home
directory implicitly, and the collector (:mod:`collector`) reads only the roots it
is given and stops on its kill switch.
Beads and events remain the authoritative record; the SQLite file is only a
derived analytical projection.
"""

__version__ = "0.8.0"

from .annotations import GoldEpisode, GoldSet, load_gold_set
from .canary import (
    CANARY_BUNDLE_SCHEMA_VERSION,
    CANARY_REGISTRATION_SCHEMA_VERSION,
    CANARY_REPORT_KIND,
    CANARY_REPORT_VERSION,
    MAX_ALLOWED_REQUESTS,
    CanaryBundle,
    CanaryGuardrails,
    CanaryRegistration,
    CanaryUnit,
    ObservedOutcome,
    assign_arms,
    assignment_digest,
    build_canary_report,
    load_canary_bundle,
    load_registration,
    normalize_canary_bundle,
    normalize_registration,
)
from .changes import (
    BUNDLE_SCHEMA_VERSION,
    OPTIMIZATION_CATEGORIES,
    build_change_bundle,
    classify_categories,
    normalize_change_bundle,
    normalize_change,
)
from .collapse import (
    ABSTAIN_LABEL,
    COLLAPSE_PROMPT_VERSION,
    COLLAPSE_REPORT_VERSION,
    DEFAULT_MAJORITY,
    PRIMARY_INTENT_COLLAPSE_V1,
    AgreementReference,
    JudgeVote,
    LabelCollapse,
    build_agreement_references,
    build_collapsed_judge_prompt,
    confusion_matrix,
    disagreement_groups,
    disagreement_pairs,
    evaluate_references,
    fleiss_kappa,
    kappa_summary,
    label_rows,
    load_judge_checkpoint,
    pairwise_cohen_kappa,
    pairwise_confusion_matrices,
    rescore_collapsed,
    resolve_collapse,
    identity_collapse,
    votes_from_checkpoint,
    votes_from_report,
    write_collapse_report,
)
from .contract import SCHEMA_VERSION, validate_record
from .episodes import Episode, EpisodeConfig, segment_events, segment_store
from .errors import (
    AnnotationError,
    CanaryError,
    ContractError,
    EpisodeError,
    EvaluationError,
    ImpactError,
    ImportConflictError,
    LabelConflictError,
    ObservatoryError,
    PolicyError,
    RegistryConflictError,
    RegistryError,
    RequestByteCapExceeded,
    RequestError,
    ResponseError,
    SchemaVersionError,
    SilverError,
    TaxonomyError,
)
from .evaluation import (
    EvaluationConfig,
    HoldoutSplit,
    Prediction,
    audit_split,
    evaluate_gold_set,
    grouped_temporal_split,
    load_predictions,
    report_json,
)
from .exposure import (
    CommitGraph,
    attach_session_fingerprints,
    build_ledger,
    evaluate_change,
    session_evidence_from_store,
)
from .impact import (
    ATTRIBUTION_GRADES,
    IMPACT_BUNDLE_VERSION,
    ImpactConfig,
    ImpactDataset,
    build_impact_report,
    load_impact_bundle,
    normalize_impact_bundle,
    observed_evidence_from_store,
)
from .jev import (
    REQUEST_BYTE_CAP,
    JevRequest,
    ResponseImport,
    build_request,
    import_response,
    validate_response,
)
from .policy import (
    CANDIDATE_KINDS,
    DECISIONS,
    DEFAULT_CONFIDENCE_THRESHOLD,
    DEFAULT_GATE_FLAGS,
    ELIGIBILITIES,
    FALLBACK_PATHS,
    POLICY_BUNDLE_VERSION,
    POLICY_CATALOG_SCHEMA_VERSION,
    POLICY_REPORT_KIND,
    POLICY_REPORT_VERSION,
    Candidate,
    ClassificationRecord,
    Feature,
    PolicyCatalog,
    PolicyConfig,
    RecommendationBundle,
    as_of_features,
    build_shadow_report,
    decision_inputs,
    load_catalog,
    load_recommendation_bundle,
    normalize_catalog,
    normalize_recommendation_bundle,
    recommendation_rows,
    recommendations_for_record,
    temporal_audit,
)
from .report import build_report
from .silver import (
    JUDGE_BACKENDS,
    JUDGE_DEEPSEEK,
    JUDGE_GEMINI38_FLASH,
    JUDGE_GLM,
    JUDGE_GPT6_LUNA,
    KAPPA_TRUST_FLOOR,
    KNOWN_JUDGES,
    MIN_PAIRWISE_OVERLAP_FRACTION,
    SILVER_REPORT_VERSION,
    AgyCLIJudgeClient,
    CandidateEpisode,
    CodexCLIJudgeClient,
    JudgeSpec,
    SilverEpisode,
    SilverResult,
    agreement_reference,
    build_judge_client,
    build_silver_result,
    cohen_kappa,
    evaluate_jev_references,
    evaluate_silver_vs_jev,
    fleiss_kappa,
    judge_label_distribution,
    load_candidates_csv,
    load_judge_config,
    overlap_meets_floor,
    pairwise_cohen_kappa,
    resolve_judge,
    resolve_judges,
    sample_stratified,
)
from .store import ObservatoryStore
from .taxonomy import load_taxonomy

__all__ = [
    "__version__",
    "SCHEMA_VERSION",
    "BUNDLE_SCHEMA_VERSION",
    "REQUEST_BYTE_CAP",
    "OPTIMIZATION_CATEGORIES",
    "ObservatoryStore",
    "JevRequest",
    "ResponseImport",
    "CommitGraph",
    "build_request",
    "import_response",
    "validate_response",
    "build_report",
    "load_taxonomy",
    "validate_record",
    "GoldEpisode",
    "GoldSet",
    "load_gold_set",
    "Episode",
    "EpisodeConfig",
    "segment_events",
    "segment_store",
    "EvaluationConfig",
    "HoldoutSplit",
    "Prediction",
    "audit_split",
    "evaluate_gold_set",
    "grouped_temporal_split",
    "load_predictions",
    "report_json",
    "normalize_change",
    "normalize_change_bundle",
    "build_change_bundle",
    "classify_categories",
    "attach_session_fingerprints",
    "build_ledger",
    "evaluate_change",
    "session_evidence_from_store",
    "ATTRIBUTION_GRADES",
    "IMPACT_BUNDLE_VERSION",
    "ImpactConfig",
    "ImpactDataset",
    "build_impact_report",
    "load_impact_bundle",
    "normalize_impact_bundle",
    "observed_evidence_from_store",
    "POLICY_BUNDLE_VERSION",
    "POLICY_CATALOG_SCHEMA_VERSION",
    "POLICY_REPORT_VERSION",
    "POLICY_REPORT_KIND",
    "CANDIDATE_KINDS",
    "DECISIONS",
    "ELIGIBILITIES",
    "FALLBACK_PATHS",
    "DEFAULT_CONFIDENCE_THRESHOLD",
    "DEFAULT_GATE_FLAGS",
    "Candidate",
    "PolicyCatalog",
    "Feature",
    "ClassificationRecord",
    "RecommendationBundle",
    "PolicyConfig",
    "normalize_catalog",
    "load_catalog",
    "normalize_recommendation_bundle",
    "load_recommendation_bundle",
    "as_of_features",
    "temporal_audit",
    "decision_inputs",
    "recommendations_for_record",
    "build_shadow_report",
    "recommendation_rows",
    "CANARY_REGISTRATION_SCHEMA_VERSION",
    "CANARY_BUNDLE_SCHEMA_VERSION",
    "CANARY_REPORT_VERSION",
    "CANARY_REPORT_KIND",
    "MAX_ALLOWED_REQUESTS",
    "CanaryGuardrails",
    "CanaryRegistration",
    "ObservedOutcome",
    "CanaryUnit",
    "CanaryBundle",
    "normalize_registration",
    "load_registration",
    "normalize_canary_bundle",
    "load_canary_bundle",
    "assignment_digest",
    "assign_arms",
    "build_canary_report",
    "SILVER_REPORT_VERSION",
    "KAPPA_TRUST_FLOOR",
    "MIN_PAIRWISE_OVERLAP_FRACTION",
    "overlap_meets_floor",
    "JUDGE_GLM",
    "JUDGE_DEEPSEEK",
    "JUDGE_GPT6_LUNA",
    "JUDGE_GEMINI38_FLASH",
    "KNOWN_JUDGES",
    "JUDGE_BACKENDS",
    "resolve_judge",
    "resolve_judges",
    "load_judge_config",
    "build_judge_client",
    "CodexCLIJudgeClient",
    "AgyCLIJudgeClient",
    "pairwise_cohen_kappa",
    "fleiss_kappa",
    "judge_label_distribution",
    "agreement_reference",
    "evaluate_jev_references",
    "CandidateEpisode",
    "SilverEpisode",
    "SilverResult",
    "JudgeSpec",
    "sample_stratified",
    "load_candidates_csv",
    "build_silver_result",
    "cohen_kappa",
    "evaluate_silver_vs_jev",
    "COLLAPSE_REPORT_VERSION",
    "COLLAPSE_PROMPT_VERSION",
    "DEFAULT_MAJORITY",
    "ABSTAIN_LABEL",
    "LabelCollapse",
    "PRIMARY_INTENT_COLLAPSE_V1",
    "AgreementReference",
    "JudgeVote",
    "resolve_collapse",
    "identity_collapse",
    "votes_from_report",
    "votes_from_checkpoint",
    "load_judge_checkpoint",
    "label_rows",
    "confusion_matrix",
    "pairwise_confusion_matrices",
    "disagreement_groups",
    "disagreement_pairs",
    "fleiss_kappa",
    "pairwise_cohen_kappa",
    "kappa_summary",
    "build_agreement_references",
    "evaluate_references",
    "rescore_collapsed",
    "build_collapsed_judge_prompt",
    "write_collapse_report",
    "ObservatoryError",
    "AnnotationError",
    "CanaryError",
    "ContractError",
    "EpisodeError",
    "EvaluationError",
    "ImpactError",
    "ImportConflictError",
    "LabelConflictError",
    "PolicyError",
    "RegistryError",
    "RegistryConflictError",
    "SchemaVersionError",
    "SilverError",
    "TaxonomyError",
    "RequestError",
    "RequestByteCapExceeded",
    "ResponseError",
]
